### ISSUE TITLE
Move LogViewer into admin module and fix other issues

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#40]
This is a master issue for current log viewer issues.

### Issues

- [ ] Move logviewer into admin module
- [ ] #464: Show slowest pages by user, etc
- [ ] #389 & #350: Build developer interface to log file analysis
- [ ] Allow user-level tracking of dashboard usage
- [ ] #414: Logviewer startup time is slow
- [ ] Needs an info icon with help for every KPI and chart
- [ ] Allow custom user interface via logviewer components
- [ ] Change the calendar component

Note on the calendar component: pick a from date, pick a to date, continue hovering. This changes the from date. Suggested behavior: don't change the from/to date until clicked.

![image](/uploads/22336ff54ad419f680b85bf57b573bc9/image.png)

### Data & Code

The log files are at `gramex.conf.variables['GRAMEXDATA']` under `logs/`. Files are:

- `requests.csv*`: each request & response made to Gramex
- `user.csv*`: user login and logout information
- `alert.csv*`: logs alerts data (optional)
- `access.csv*`: old Gramex logs. Ignore this
- `gramex.log*`: new Gramex logs. Ignore this

Code is at [gramex/apps/logviewer/](https://code.gramener.com/cto/gramex/tree/master/gramex/apps/logviewer/). @pratap.vardhan is the author.

### Needs

We want to create admin/logviewer as a series of individual components that addresses these needs:

- What is the traffic trend:
  - metrics: page views, sessions
  - time periods: daily, weekly, monthly
- What is the site responsiveness trend:
  - metrics: response time
  - time periods: daily, weekly, monthly
- Which are the top items:
  - metrics: page views, sessions
  - groups: page, user, status, ip
- Which are the slow pages:
  - metrics: response time
  - groups: user, page
- Who used which dashboard the most:
  - metrics: page views, sessions, session duration
  - groups: user, page
- Filters
  - time period: current component
  - page: only HTML pages. Prioritize dashboard pages
  - user: grouped by domain, multi-select by domain
  - HTTP status: current component

### Principles

- All information is aggregated at a daily level or slower

### Next steps

Phase 1: Migrate logviewer backend to `admin/log/`
- [x] Speak to @dipika.verma to understand the pending issues above
- [x] Speak to @pratap.vardhan to understand the code base
- [x] Create a separate branch called `logviewer-admin` to migrate logviewer as-is into admin module
- [ ] Move the existing `logviewer.py` and `gramex.yaml` schedule into admin page and test that the back-end FormHandler endpoints work
- [ ] Review with @s.anand 

Phase 2: Create simple front-end components in `admin/log/`
- [ ] Create and document the FormHandler tables / charts required to build a custom log viewer interface
- [ ] Create a simple log viewer interface that addresses as many needs as possible
- [ ] Review with @s.anand and project teams

Phase 3: Integrate all components required into `admin/log/` page

- Source: <https://code.gramener.com/cto/gramex/issues/585>
- Author: [s.anand](https://code.gramener.com/s.anand)
- Created: Thu 10 Jan 2019 05:22
