### ISSUE TITLE
gramextest improvements: master issue

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#91]
This is a master issue for work-in-progress issues on gramextest.
Once separate issues have been created for these, mark them done.

- [ ] Run specific tests from the admin panel
- [ ] Add arbitrary Python (extend tests with new functionality)
- [ ] Add screenshot
- [ ] Add performance and load testing (including lighthouse)
- [ ] Add security testing
- [ ] XPATH and CSS can be complex. Can we simplify?
- [ ] How can we trace back to requirements?
- [ ] How can we align with JIRA test cases?
- [ ] gramextest is slow to start. How can we speed it up?

**Comment by sanand0** [comment]
Closed since `gramextest` is deprecated #266
